# Configuração do plugin de Factions
# Somente tablist por enquanto

tablist:
  headerLines:
    - ''
    - '&6&lHYZE'
    - ''
  footerLines:
    - ''
    - '&fPrecisa de ajuda? Acesse nosso Discord!'
    - '&7discord.gg/hyze'
    - ''
    - '&6lojar.hyze.net'
    - ''
