axe-damage:
  WOODEN_AXE: 6.0
  GOLDEN_AXE: 6.0
  STONE_AXE: 8.0
  IRON_AXE: 10.0
  DIAMOND_AXE: 12.0
  NETHERITE_AXE: 14.0
sword-damage:
  WOODEN_SWORD: 4.0
  GOLDEN_SWORD: 4.0
  STONE_SWORD: 5.0
  IRON_SWORD: 6.0
  DIAMOND_SWORD: 7.0
  NETHERITE_SWORD: 8.0
