mysql:
  host: minecraft
  port: 3306
  database: minecraft
  user: root
  password: minecraft

enable-scoreboard: true
enable-tablist: true
update-interval-ticks: 20  # 1 second

spawn:
  world: world
  x: 0
  y: 80
  z: 0
  yaw: 0
  pitch: 0

# ----- Scoreboard -----
scoreboard:
  title: '&cCOMMUNITY'
  update-interval-ticks: 20
  lines:
    - '&0 '                         # linha em branco (única por conter &0)
    - '&7Lobby: &f#3'
    - '&7 '                         # outra linha em branco
    - '&c# Factions Fire:'
    - '&a%online%/&c500 jogando!'
    - '&7 '                         # em branco
    - '&7CP: &f%cp%'
    - '&7Cash: &6%cash%'
    - '&8 '                         # em branco final
    - '&8redecommunity.com'

# ----- TabList -----
tablist:
  header: '&cCOMMUNITY'
  footer: '&8redecommunity.com'

# ----- Servidores -----
servers:
  - slot: 11
    head-owner: Notch
    name: '&cFactions'
    lore:
      - '&7Servidor focado em Factions'
    server: factions
  - slot: 15
    item: GRASS_BLOCK
    name: '&aSkyWars'
    lore:
      - '&7Entre em partidas rápidas de SkyWars'
    server: skywars
