name: lobby
main: conexao.code.lobby
version: 1.0-SNAPSHOT
api-version: 1.13
commands:
  recarregar:
    description: Recarrega o scoreboard e tablist do lobby
    usage: /recarregar
    aliases: [reload]
  setspawn:
    description: Define o spawn do lobby
    usage: /setspawn
    aliases: [setlobbyspawn]
  trocarsenha:
    description: Altera sua senha
    usage: /trocarsenha <senha-antiga> <senha-nova>
  sethologram:
    description: Define a localização do holograma do lobby
    usage: /sethologram
permissions:
  lobby.reload:
    description: Permite usar /recarregar
    default: op
  lobby.setspawn:
    description: Permite definir o spawn do lobby
    default: op
  lobby.sethologram:
    description: Permite definir a posição do holograma
    default: op
