name: lobby
main: conexao.code.lobby
version: 1.0-SNAPSHOT
api-version: 1.13
commands:
  recarregar:
    description: Recarrega o scoreboard e tablist do lobby
    usage: /recarregar
    aliases: [reload]
  setspawn:
    description: Define o spawn do lobby
    usage: /setspawn
    aliases: [setlobbyspawn]
permissions:
  lobby.reload:
    description: Permite usar /recarregar
    default: op
  lobby.setspawn:
    description: Permite definir o spawn do lobby
    default: op
